HYC - 1887 - Updated Analytics for Matomo Integration
UNC-Libraries/hy-c pull request #1091
Opened 2024-04-02 23:32 UTC by davidcam-src

https://unclibrary.atlassian.net/browse/HYC-1887

* Download analytics sends a request to matomo for tracking instead of GA4
* Modified tests to reflect changes to download analytics
* Rolled back stats controller override for returning 404 on stats related pages
* Matomo override introduced for retrieval of page view and download stats
* Tracking tag with some changes to include custom dimensions included in `_matomo.html.erb`

2024-04-08 21:12 UTC, bbpennel requested changes

2024-04-08 21:12 UTC, bbpennel commented on app/controllers/concerns/hyc/download_analytics_behavior.rb
> +      def user_id
don't think this is used anymore

2024-04-08 21:12 UTC, bbpennel commented on app/views/hyrax/file_sets/_show_actions.html.erb
> +  <% if Hyrax.config.analytics? %>
same here

2024-04-08 21:12 UTC, bbpennel commented on spec/fixtures/files/matomo_work_downloads.json
is this file still needed?

2024-04-08 21:12 UTC, bbpennel commented on spec/fixtures/files/matomo_work_views.json
is this file still needed?

2024-04-09 14:00 UTC, davidcam-src commented on app/views/hyrax/base/_show_actions.html.erb
> -    <% if Hyrax.config.analytics? && Hyrax.config.analytics_provider != 'ga4' %>
Gotcha, thanks for explaining this. I'll rollback the change

2024-04-09 15:57 UTC, merged