HYC-1882 - Dimensions Ingest Service
UNC-Libraries/hy-c pull request #1095
Opened 2024-04-21 23:06 UTC by davidcam-src

https://unclibrary.atlassian.net/browse/HYC-1882

* Introducing class to process new publications from dimensions and add them to the existing repository as well as tests

2024-04-22 22:02 UTC, bbpennel requested changes

2024-04-22 22:02 UTC, bbpennel commented on spec/services/tasks/dimensions_ingest_service_spec.rb
> +    .to_return(body: pdf_content, status: 200, headers: { 'Content-Type' => 'application/pdf' })
indent

2024-04-23 13:21 UTC, bbpennel commented on app/services/tasks/dimensions_ingest_service.rb
> +        'name' => "#{[author['first_name'], author['last_name']].compact.join(' ')}",
I checked with rebekah, and it sounds like she'd prefer "last, first" format for the names, which I think should be a minor adjustment to what you have here.

2024-04-23 14:27 UTC, bbpennel commented on app/services/tasks/dimensions_ingest_service.rb
> +    def format_funders_data(publication)
Anna suggests that we just store the funder name to the funder field, instead of storing the pipe delimited set of all fields. Once things move along further with ROR we will want to circle back to this, but there's a decent likelihood that we would want to put the extra details into new ROR related fields.

2024-04-23 16:24 UTC, davidcam-src commented on app/services/tasks/dimensions_ingest_service.rb
> +        raise "Incorrect content type: '#{response.headers['content-type']}'" unless response.headers['content-type'] && response.headers['content-type'].include?('application/pdf')
Adding extra handling could be beneficial and I'm open to adding it if you think we should.

2024-04-23 16:33 UTC, davidcam-src commented on app/services/tasks/dimensions_ingest_service.rb
> +        filename = "downloaded_pdf_#{Time.now.to_i}.pdf"
Nice catch! Thanks

2024-04-23 17:02 UTC, davidcam-src commented on app/services/tasks/dimensions_ingest_service.rb
> +        Rails.logger.error("Failed to retrieve PDF from URL '#{pdf_url}'. #{e.message}")
Gotcha, I just made it so the extract pdf function also adds a key value pair `publication['pdf_attached'] = true` or `publication['pdf_attached'] = false` and changed the error to a warning.

2024-04-23 17:15 UTC, davidcam-src commented on spec/services/tasks/dimensions_ingest_service_spec.rb
> +          expect(fs.parent).to eq(processed_publication)
Sounds good, I think it was just a style decision at the time

2024-04-23 17:25 UTC, davidcam-src commented on spec/services/tasks/dimensions_ingest_service_spec.rb
> +      end
this will probably be more useful for the email report tests, I'll remove it

2024-04-24 13:50 UTC, bbpennel requested changes

2024-04-24 13:50 UTC, bbpennel commented on app/services/tasks/dimensions_ingest_service.rb
> +      unc_grid_id = 'grid.410711.2'
This should most likely be a constant

2024-04-24 13:50 UTC, bbpennel commented on app/services/tasks/dimensions_ingest_service.rb
> +      publication&.[]=('pdf_attached', false)
Can `publication` actually be nil? If that is the case, it might make more sense to catch that in `ingest_publications` and skip over the publication, versus having to deal with it every time publication is used

2024-04-24 13:50 UTC, bbpennel commented on app/services/tasks/dimensions_ingest_service.rb
> +    end
Looks like the last `end` got some extra indents

2024-04-24 13:50 UTC, bbpennel commented on app/services/tasks/dimensions_ingest_service.rb
> +        raise "Incorrect content type: '#{response.headers['content-type']}'" unless response.headers['content-type'] && response.headers['content-type'].include?('application/pdf')
Sure, we might as well, it seems like the download links can come from a wide variety of servers, so it's possible some of them will behave differently. You should be able to do the same content-type check as part of the GET request (although keeping the head request too is a good idea)

2024-04-24 17:03 UTC, bbpennel approved these changes

2024-04-24 17:05 UTC, merged