HYC-1678 - Dimensions Ingest Rake Task
UNC-Libraries/hy-c pull request #1103
Opened 2024-06-11 21:59 UTC by davidcam-src

https://unclibrary.atlassian.net/browse/HYC-1678

* Introduces dimensions ingest rake task and helper class
* Updates action configuration for dev/test/production environments
* Slight changes made to headers in dimensions query service to get around 400 error codes from deimensions

2024-06-18 14:31 UTC, bbpennel requested changes

2024-06-18 14:31 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +    file_path = Rails.root.join('log', 'last_dimensions_ingest_run.txt')
I believe that we would want to store this outside of the rails root, since we'll end up with a fresh log directory every time we deploy. I would suggest either something in `ENV['DATA_STORAGE']` or in `/logs/hyc/` (which you could probably get via `ENV['LOGS_PATH`]` and then getting the parent directory).

2024-06-18 14:31 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +      formatted_last_run_time = last_run_time.strftime('%Y-%m-%d')
this looks the same as line 17

2024-06-18 14:31 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +      'depositor_onyen' => 'admin'
This might need to be configurable. I don't think there is an `admin` user in prod. We've tended to use rebekah as the depositor onyen for most stuff, which is maybe questionable long term, but prod is restrictive about creating users

2024-06-18 14:31 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +      Rails.logger.error "Failed to send test email: #{e.message}"
```suggestion
      Rails.logger.error "Failed to send email: #{e.message}"
```

2024-06-18 14:31 UTC, bbpennel commented on app/services/tasks/dimensions_query_service.rb
> +      # end
can remove

2024-06-18 14:31 UTC, bbpennel commented on app/services/tasks/dimensions_query_service.rb
> +    def handle_query_error(error, retries)
Feel free to ignore this one, but I find the mix of retries being handled inside and outside this method a bit confusing. This method could be refocused to `query_needs_retry?(retries)`, and then we'd have

```
# This is up at line 53
Rails.logger.error("HTTParty error during Dimensions API query: #{error.message}")
retry if query_needs_retry?(retries)
raise e

...

def query_needs_retry?(retries)
      retries += 1
      if retries <= MAX_RETRIES
        Rails.logger.warn("Retrying query after #{2**retries} seconds. (Attempt #{retries + 1} of #{MAX_RETRIES})")
        sleep(2**retries) # Using base 2 for exponential backoff
        return true
      end
      false
end
```

(Although in either implementation it might end up logging the error twice when it runs out of retries, so logging of the error could be done conditionally only when there are retries remaining)

2024-06-18 17:21 UTC, davidcam-src commented on lib/tasks/dimensions_ingest.rake
> +      'depositor_onyen' => 'admin'
That sounds reasonable. How would you suggest changing it? I was thinking of introducing an environment variable. Something like:

DIMENSIONS_INGEST_DEPOSITOR_ONYEN = admin (dev, test) rebekah (prod)

2024-06-18 19:00 UTC, davidcam-src commented on app/services/tasks/dimensions_query_service.rb
> +    def handle_query_error(error, retries)
Appreciate the suggestion, great idea. I implemented the change but made it so retries is still incremented inside of query_dimensions. For some reason retries doesn't update properly when it's incremented inside of the needs_retry function.

2024-06-19 14:04 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +      'depositor_onyen' => 'admin'
yeah an environment variable would make sense

2024-06-19 14:25 UTC, bbpennel commented on app/services/tasks/dimensions_query_service.rb
> +    def handle_query_error(error, retries)
Apparently ruby passes integer variables by value rather than reference, so if we wanted to be able to increment it in both places we'd have to do something weird like wrap it in an array
```
retries = [0]

def query_needs_retry?(retries)
   retries[0] += 1
   ...
```

Either way, we should make use of the return value from the method in the rescue block, so:
```
        rescue HTTParty::Error, StandardError => e
          retries += 1
          retry if query_needs_retry?(e, retries)
          raise e
        end
```

2024-06-19 16:20 UTC, bbpennel commented on spec/services/tasks/dimensions_reporting_service_spec.rb
> +    allow(User).to receive(:find_by).with(uid: ENV['DIMENSIONS_INGEST_DEPOSITOR_ONYEN']).and_return(admin)
For tests, particularly when we're defining the value in the test itself, it's fine and probably preferable to keep the actual value in assertions and mocks, since it's a good bit more readable and the environment is consistent

2024-06-19 17:29 UTC, davidcam-src commented on app/services/tasks/dimensions_query_service.rb
> +    def handle_query_error(error, retries)
Sorry I thought I had already made the change to make use of the return value. I've made updates to do that as well as wrap 'retries' in an array.

2024-06-19 17:59 UTC, bbpennel approved these changes

2024-06-19 18:03 UTC, merged