HYC 1932 - Update Dimensions Workflow
UNC-Libraries/hy-c pull request #1104
Opened 2024-06-25 21:41 UTC by davidcam-src

https://unclibrary.atlassian.net/browse/HYC-1932

A bunch of stuff came up during testing, I made some improvements based on our discussions in the above ticket and some other quality of life changes. Including a little more detail than usual since I figure the PR would be difficult to follow otherwise:

* Changed mapping in DimensionsIngestService to:
  - set `N/A` as the default value if a publication doesn't have an abstract
  - map `concepts` from publications to `fields` in new Articles
  - fetch exclusively the first affiliation for authors to map to `other_affiliations` for creators
 * Changes to DimensionsQueryService:
   - Required start and end_date arguments for query_dimensions. When an earliest date isn't provided the default value is provided from the rake task and I assume the function won't be used much outside of that context **(lines 16-22)**
   - Changed some of the formatting at the start of the query dimensions service. Optional arguments weren't working properly before **(lines 15-18)**
   - Added `dimensions_total_count` class attribute to be used for reporting the amount of publications returned from Dimensions in the email reports **(12-13)**
    - Split the code from `deduplicate_publications` into separate functions since it was getting a bit bloated **(133-185)**
    - Change query string to search inbetween two dates and return fields to include `concepts` **(200-202)**
 * Changes to ReportingService:
     - Specify if the job was run automatically or manually **(17)**
     - Include date range and the amount of publications returned from Dimensions **(18,20)**
 * Updated report email template to include a date range and updated header
 * Changes to Dimensions Rake Task:
     - Take `admin_set`, `start_date` and `end_date` as arguments
     - Require that either bother `start_date` and `end_date` are both provided or neither **(14-19)**
     - Conditionally parse start and end dates. Either `start_date, end_date = provided arguments` or `start_date, end_date = previous_run_time, Today` **(21-40)**
  * Updated query response test fixture to consolidate publications with and without DOIs into one file since the ones without DOIs were mostly there to test marked for review functionality that's been removed
  * Updated ingest test fixture to include a publication with multiple authors to test mapping for authors to creators
  * Changes to DimensionsIngestService Tests:
     - `creates an article with metadata` recovers the article added to our test fixture with multiple creators and checks the mapping for all of them
     - check for abstract and keyword mapping **(265-266)**
     - check for default values in case a publication doesn't have concepts or an abstract **(282-290)**
  * Changes to DimensionsReportingService Tests:
      - check that the service describes the job as manually executed if the argument `is_cron_job` is false **(103-108)**

2024-06-27 19:29 UTC, bbpennel requested changes

2024-06-27 19:29 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +      File.open(Rails.root.join('log', 'last_dimensions_ingest_run.txt'), 'w') do |f|
This isn't the same path as used above for addressing the `last_dimensions_ingest_run.txt` file. I'd suggest adding a helper method to the rake task to compute the path.

2024-06-27 19:29 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +      end
just a readability suggestion, but it might be nice to put all this into a helper method like `get_last_run_time` since this is a rather long method and that's a fairly well contained task.

2024-06-27 19:29 UTC, bbpennel commented on spec/mailers/previews/dimensions_report_mailer_preview.rb
>  class DimensionsReportMailerPreview < ActionMailer::Preview
I'm realizing i don't actually know how the Preview class works. Does this have to be executed like a test, or does it execute when you access the URL in the comment at the top of the file?

2024-06-27 19:29 UTC, bbpennel commented on spec/services/tasks/dimensions_ingest_service_spec.rb
> +      all_creators_names = article.creators.map { |creator| creator.attributes['name'] }
We should probably assert how many authors are expected, since this test could still pass if the expected_author_metadata assignment above didn't work correctly and didn't load any authors or there were more authors in the generated article than expected.

2024-06-27 20:12 UTC, davidcam-src commented on app/services/tasks/dimensions_query_service.rb
> +      new_publications = publications.reject do |pub|
I didn't know this was a thing, thanks for mentioning it.

2024-06-27 20:13 UTC, davidcam-src commented on app/services/tasks/dimensions_query_service.rb
> +      search_clauses = ['where type = "article"', "date >= \"#{start_date}\"", "date <= \"#{end_date}\""].join(' and ')
That makes complete sense, I could see how that would be an issue. I just made it so that the end date isn't included.

2024-06-27 20:31 UTC, davidcam-src commented on spec/mailers/previews/dimensions_report_mailer_preview.rb
>  class DimensionsReportMailerPreview < ActionMailer::Preview
I believe your second assumption was correct. Including a quote from ChatGPT I thought could be helpful:

> The Preview class in Rails executes when you access the URL specified in the comment at the top of the file. This URL is a special preview URL generated by Rails that allows you to preview your mailer without sending it. So, when you navigate to this URL in your browser, Rails renders the email preview based on the corresponding methods defined in the Preview class. You don't need to run it like a test; simply accessing the URL triggers the execution and renders the preview

2024-06-28 12:55 UTC, bbpennel requested changes

2024-06-28 12:55 UTC, bbpennel commented on spec/services/tasks/dimensions_ingest_service_spec.rb
> +      all_creators_names = article.creators.map { |creator| creator.attributes['name'] }
Since expected_author_metadata is programmatically populated, if a bug arose that affected the population of this variable (like the way authors were stored in the input changed), we could incorrectly have this test pass since both expected_author_metadata and article.creators could be empty. It's less flexible, but I would suggest hard coding the expected count, which would also make it easier to understand what is expected when reading the code.

2024-06-28 12:55 UTC, bbpennel commented on lib/tasks/dimensions_ingest.rake
> +  def self.get_last_run_time(args)
The scope of this helper is a bit bigger than what I had highlighted originally, which is fine, I'd just suggest reflecting that in the method name, maybe "get_date_range".

Also, while functionally identical, my understanding is that `true` and `false` are the preferred values for assigning boolean variables, while the all caps versions are mostly intended for assigning values to constants, but I don't feel strongly about it.

2024-06-28 14:21 UTC, bbpennel approved these changes

2024-06-28 14:32 UTC, merged