HYC-1354 - Fallback Thumbnails
UNC-Libraries/hy-c pull request #1133
Opened 2024-11-26 22:47 UTC by davidcam-src

2024-12-04 15:12 UTC, bbpennel requested changes

2024-12-04 15:12 UTC, bbpennel commented on app/overrides/presenters/hyrax/work_show_presenter_override.rb
> -           :rendering_ids, :member_of_collection_ids, :alternative_title, :bibliographic_citation, to: :solr_document
did we mean to remove `bibliographic_citation`? I see it as an admin only field for articles and included as a show field in catalog_controller, although i don't know if work_show_presenter impacts them.

2024-12-04 15:12 UTC, bbpennel commented on spec/presenters/blacklight/thumbnail_presenter_spec.rb
> +      presenter.send(:retrieve_values, field_config)
Since this method returns a value (and that seems to be its main purpose), it seems like we would want to verify the outputs as well, here and in the other test

2024-12-05 15:08 UTC, davidcam-src commented on app/overrides/presenters/hyrax/work_show_presenter_override.rb
> +    return nil if primary_fileset_id.blank?
moved this into the `@representative_presenter ||= ` block

2024-12-05 15:08 UTC, davidcam-src commented on app/overrides/presenters/blacklight/thumbnail_presenter_override.rb
> +      # Check if the thumbnail path is the default or missing and file_set_ids are present
I've updated the comment and split up the condition on the last line a bit

2024-12-05 20:09 UTC, bbpennel approved these changes

2024-12-05 20:51 UTC, merged