Add methods to base actor to apply work-specific workflow permissions
UNC-Libraries/hy-c pull request #567
Opened 2020-10-12 18:18 UTC by smithjp

* https://jira.lib.unc.edu/browse/HYC-992

2020-10-13 18:34 UTC, bbpennel requested changes

2020-10-13 18:34 UTC, bbpennel commented on app/actors/hyrax/actors/base_actor.rb
> +            if !v['index'].blank?
is the presence of the `index` field new in this PR or has it been there a while, you're just taking this opportunity to clean it up since you're already doing stuff with permissions? Which is fine, I'm just trying to understand if its possible to prevent it from appearing in the first place, or if its better to clean it up afterwards.

2020-10-13 18:34 UTC, bbpennel commented on app/actors/hyrax/actors/base_actor.rb
> +        next_actor.create(env) && run_callbacks(:after_create_concern, env)
Will it cause any issues that the `save` method is no longer a part of the return value for this method?

2020-10-13 18:34 UTC, bbpennel commented on app/actors/hyrax/actors/base_actor.rb
> +          if !permission['id'].blank?
could you add a comment describing why the presence of an id for a permission means that it doesn't need to add in the work-specifc workflow details?

2020-10-13 18:34 UTC, bbpennel commented on app/actors/hyrax/actors/base_actor.rb
> +      # added this method to allow work-specific permissions to work
maybe add `[hyc-override]` to this comment?

2020-10-13 18:34 UTC, bbpennel commented on app/actors/hyrax/actors/base_actor.rb
> +      # added this method to allow work-specific permissions to work
maybe add `[hyc-override]` to this comment?

2020-10-13 18:34 UTC, bbpennel commented on app/actors/hyrax/actors/base_actor.rb
>          # [hyc-override] Overriding actor to cast rights statements as single valued
i know its not part of this PR, but should this comment be above line 93?

2020-10-14 19:41 UTC, smithjp commented on app/actors/hyrax/actors/base_actor.rb
> +            if !v['index'].blank?
This is something I found while working on this ticket, and I had to fix it in order to get things working.  I'm not sure where the index param is coming from.

2020-10-14 19:41 UTC, smithjp commented on app/actors/hyrax/actors/base_actor.rb
>          # [hyc-override] Overriding actor to cast rights statements as single valued
yes, i wasn't sure what that was.  it appears to be a comment that was supposed to indicate that a line of code was removed.  i will add a comment.

2020-10-16 14:42 UTC, bbpennel commented on app/actors/hyrax/actors/base_actor.rb
>          # [hyc-override] Overriding actor to cast rights statements as single valued
ah, so its a removed line? I wasn't sure if it was referring to `attributes[:license] = Array(attributes[:license]) if attributes.key? :license`

2020-10-23 21:50 UTC, merged