WIP: Gh actions
UNC-Libraries/hy-c pull request #607
Opened 2021-02-18 20:29 UTC by lfarrell

https://jira.lib.unc.edu/browse/HYC-865

2021-02-22 14:20 UTC, bbpennel requested changes

2021-02-22 14:20 UTC, bbpennel commented on .github/workflows/build.yml
> +    - name: Cache Maven packages
Is this needed? I don't think anything is being build with maven here.

2021-02-22 14:24 UTC, lfarrell commented on .github/workflows/build.yml
> +    - name: Cache Maven packages
Yeah, probably not.

2021-02-23 16:09 UTC, bbpennel approved these changes

2021-02-23 16:10 UTC, merged