OAI endpoint tests passing locally
UNC-Libraries/hy-c pull request #712
Opened 2021-11-23 17:15 UTC by maxkadel

2021-11-23 18:32 UTC, bbpennel commented on spec/requests/oai_pmh_endpoint_spec.rb
> +    solr = Blacklight.default_index.connection
I assume with this methodology that if there are any changes to indexing we will need to represent them in the sample document? It may be valuable to document how you generated the file since we'll likely have to update it in the future.

Also, is there anything else in the index prior to this deletion aside from the sample documents? I half remember hyrax putting entries in for every fedora object, rather than just the works. Is there any chance that wiping the index will impact other tests, since I thought I remember you mentioning that there is the potential for modifications from one test affecting other tests?

2021-11-23 18:32 UTC, bbpennel commented on spec/requests/oai_pmh_endpoint_spec.rb
> +        # TODO: freeze time, so if the test is slow we won't get strange failures
While I love this comment and the special effects that go with it, seems like it'd make sense to go ahead and do that as part of this PR unless its impractical to do so?

2021-11-23 19:32 UTC, maxkadel commented on spec/requests/oai_pmh_endpoint_spec.rb
> +    solr = Blacklight.default_index.connection
Good call on documenting how I did it - it didn't make sense to me to totally script it, but I've put it in the readme, and if we decide we're doing it enough to need to script it we can do that. 

So, right now, we are running a rake task that runs all the tasks in the SetupTasksService, including importing test data, which creates fairly full-fledged objects in both Fedora and Solr. The problem is that the task is fairly slow, so for development you just run it once, then hope that your tests don't change any of the objects. 

I want to shift to a) running the tests in random order, so we raise any order dependencies before we hit them in production (there's a ticket in the backlog for this) and b) be much more explicit about what we can and cannot expect to exist in the context of any test, and do the minimal setup possible for that test. 

This takes us one step towards those things, and doesn't make the current test suite any more broken locally or in CI than it was before, so I think it's an improvement.

2021-11-23 19:35 UTC, maxkadel commented on spec/requests/oai_pmh_endpoint_spec.rb
> +        # TODO: freeze time, so if the test is slow we won't get strange failures
I put the timestamps in the solr documents, so we don't need this any more. Before, it was dependent on whenever the rake task had saved the work to solr, and that each of those saves happened on a different second, and if two were saved too close together some of the tests would fail. So, we're fixing that, and we don't need to freeze time! Although that can be a super handy tool if the test is explicitly about time passing. https://api.rubyonrails.org/v5.2.6/classes/ActiveSupport/Testing/TimeHelpers.html

2021-11-23 22:34 UTC, bbpennel requested changes
Two minor suggestions

2021-11-23 22:34 UTC, bbpennel commented on README.md
> +  * Search in your development environment front end to find the ID for the object you you want to update (if using the UNC-CH VM this will be at localhost:4040, if you are running it locally on the
Extra "you", should be: `ID for the object you want to update`

2021-11-23 22:34 UTC, bbpennel commented on README.md
> +    * Copy the output of this to the sample_solr_documents file. You may need to add a `:timestamp` in order for the `spec/requests/oai_pmh_endpoint_spec.rb` test to continue to pass.
Please state under what circumstance you would need to add a `:timestamp`

2021-11-24 18:59 UTC, bbpennel approved these changes

2021-11-24 18:59 UTC, merged