WIP: Unzip sage
UNC-Libraries/hy-c pull request #728
Opened 2021-12-10 14:24 UTC by maxkadel

2021-12-14 20:45 UTC, bbpennel requested changes
Looks good over all, a number of my questions probably stem from not being sure what the intent of the .done files is

2021-12-14 20:45 UTC, bbpennel commented on app/services/tasks/sage_ingest_service.rb
> +        orig_file_name = package_path.split('.zip')[0].split('/')[-1]
Would one of the options listed here make sense rather than using multiple splits? What you have is might be more efficiency, but a bit hard to read:
https://stackoverflow.com/questions/374326/how-to-get-filename-without-extension-from-file-path-in-ruby

2021-12-14 20:45 UTC, bbpennel commented on app/services/tasks/sage_ingest_service.rb
> +        mark_pdf_done(unzipped_package_dir) if pdf_complete?(unzipped_package_dir, pdf_file_name)
Earlier in the loop you are checking that there are exactly 2 files in the package. Since it seems like both files must always be present, under what scenario will you not want to mark either the PDF or XML as done? Should the whole object be rolled back if either one is not present? Is this for a resumption scenario? I may be misunderstanding, but even in that scenario it seems like either both or neither files should be done.

2021-12-14 20:45 UTC, bbpennel commented on app/services/tasks/sage_ingest_service.rb
> +    end
Should there be a cleanup step for the extracted zip files after they are ingested? Are you anticipating needing to support resuming an incomplete batch of deposits, and if so, what mechanism are you hoping to use for that? I think we've used progress logs in some of the other scripts, which in this case would probably need to record the original file name. I wasn't sure if that was the intent of the .done files here, which would require keeping the extra unzipped files.

2021-12-14 21:54 UTC, maxkadel commented on app/services/tasks/sage_ingest_service.rb
> +        mark_pdf_done(unzipped_package_dir) if pdf_complete?(unzipped_package_dir, pdf_file_name)
- What I was thinking of for the .done file was trying to think through when we should delete or archive the files on the server, and that making sure there's a .done file could be a step for a separate cleanup step. Maybe this is pre-optimization? 
- We are going to need to do different types of processing for xml and pdf files - xml files get parsed and turned into the metadata for the object, pdf files get attached to the object and persisted (this is a hand-wave-y summary). Right now the x_complete? method is a placeholder for other checks we might want to do to make sure that everything is in its place for each type of document handling. 

So, that was my thinking, but I'm pondering whether it should be a single .done file and complete? method.

2021-12-14 21:55 UTC, maxkadel commented on app/services/tasks/sage_ingest_service.rb
> +      FileUtils.touch(File.join(unzipped_package_dir, ".done.pdf"))
Good point - so, earlier in the process, check whether the .done file exists, and if so, move to the next object?

2021-12-14 22:18 UTC, maxkadel commented on app/services/tasks/sage_ingest_service.rb
> +    end
My thought was that we would want to clean up the working files after the entire batch was ingested - at the scale we have now, I don't anticipate that being a problem, but if it ramps up significantly we'll probably need to revisit it.

We do want to be able to resume incomplete batches, but I'm not totally clear on how we want to do that - I've tried to replicate the logging the proquest ingest has - is there another service you would recommend I look at?. 

Part of the intention of creating the .done file at this step is also just to make sure we're successfully unzipping the resources and know where the files are, in a way that a human can see at the end. We won't necessarily keep it, but it's scaffolding for the next steps.

2021-12-14 22:18 UTC, maxkadel commented on spec/services/tasks/sage_ingest_service_spec.rb
> +        end.to change { Dir.entries(first_dir_path).count }.from(4).to(5)
Yup, good idea.

2021-12-14 22:19 UTC, maxkadel commented on spec/services/tasks/sage_ingest_service_spec.rb
> +    context "with a give file already present" do
typo - good catch

2021-12-14 22:19 UTC, bbpennel commented on app/services/tasks/sage_ingest_service.rb
> +        mark_pdf_done(unzipped_package_dir) if pdf_complete?(unzipped_package_dir, pdf_file_name)
We will need to do different types of processing for the two files, but it seems like attaching the PDFs won't happen unless the XML parsing succeeds? And we wouldn't want to commit the work unless the PDF attached successfully.  I can't remember if you can wait until the work and its filesets have been created before saving everything. If so, then you would only need to track that the package completed. If not, then you would probably need to record both work creation and pdf attachment separately.

The zip file will still exist after extracting it, won't it? So cleaning up the extracted files should not pose any data loss risk. Only needing to record a single entry per package would be preferable, whether its a .done file or a progress log.

2021-12-14 22:22 UTC, bbpennel commented on app/services/tasks/sage_ingest_service.rb
> +      FileUtils.touch(File.join(unzipped_package_dir, ".done.pdf"))
yes, having a check for if an object is done as early in the loop as possible would make sense.

2021-12-14 22:36 UTC, bbpennel commented on app/services/tasks/sage_ingest_service.rb
> +    end
Its really an implementation detail how progress gets tracked, so I don't want to push on this too much. Apparently the progress log setup isn't used for the proquest script, maybe because it is fairly small batches. The utility I was thinking of is this thing:
https://github.com/UNC-Libraries/hy-c/blob/431427d061465d3aa5ba2ac6e0687a2ad98b3a5b/lib/tasks/migrate/services/progress_tracker.rb

Its used by a number of the bulk utility scripts in hyc and hyc-utils:
https://github.com/UNC-Libraries/hy-c/search?q=ProgressTracker

It's up to you which approach you prefer and think will work best for this scenario.

2021-12-15 14:11 UTC, maxkadel commented on app/services/tasks/sage_ingest_service.rb
> +        mark_pdf_done(unzipped_package_dir) if pdf_complete?(unzipped_package_dir, pdf_file_name)
Ok, that makes sense to me, I can change that, and adjust the ticket to reflect that.

2021-12-16 14:00 UTC, bbpennel commented on app/services/tasks/sage_ingest_service.rb
> +      return true if File.exist?(File.join(dir, file_names.first)) && File.exist?(File.join(dir, file_names.last))
I'm not totally sure what this checks purpose is after the object has already been ingested, but I understand that we don't know what all the assertions are to verify that the package was ingested yet, so its fine for now

2021-12-16 14:05 UTC, bbpennel commented on spec/services/tasks/sage_ingest_service_spec.rb
> +      expect(File.size(ingest_progress_log_path)).to eq 37
up to you if you want to change it, but the contents of the progress log should be pretty predictable, so you could assert that the progress log contains the expected filename rather than or in addition to checking the file size.

2021-12-16 15:48 UTC, merged