Refactor ingest
UNC-Libraries/hy-c pull request #752
Opened 2022-01-31 21:40 UTC by maxkadel

2022-02-03 21:08 UTC, bbpennel requested changes
This looks like a good refactoring over all, left a few suggestions and questions

2022-02-03 21:08 UTC, bbpennel commented on spec/services/tasks/proquest_ingest_service_spec.rb
> +      expect(Dir.entries(unzipped_dir)).to match_array(['.', '..', '__MACOSX', 'attach_unc_1.pdf', 'attach_unc_1_DATA.xml', 'attach_unc_1_attach'])
Is `__MACOSX` something we need to test for? Could check that that array contains `'attach_unc_1.pdf', 'attach_unc_1_DATA.xml', 'attach_unc_1_attach'` instead of doing a full match_array.

2022-02-03 21:08 UTC, bbpennel commented on lib/tasks/proquest_ingest.rake
> +    Tasks::ProquestIngestService.new(args).process_packages
Mostly personal preference, but I would probably avoid having `process_packages` and `process_package` since I tend to miss the `s` and get mixed up about which one is being called (I lost about 10 minutes on an earlier PR before I realized there was a  pluralized and unpluralized version of a method)

2022-02-07 16:23 UTC, maxkadel commented on app/services/tasks/ingest_service.rb
> +      @deposit_record_hash ||= { title: "#{ingest_source} Ingest #{Time.new.strftime('%B %d, %Y')}",
The ingest isn't currently set up to automatically resume if it fails or is interrupted (nor is the ProQuest ingest at this time). 

If we run the same command to kick off the ingest a second time, on the same day, it would create a new DepositRecord with an automatically-generated title, and that title would be the same if they were run on the same day. 

We could use a longer timestamp to differentiate them, if we think it is or will soon be an issue?

2022-02-07 16:24 UTC, maxkadel commented on app/services/tasks/ingest_service.rb
> +      logger.info("Completing ingest of #{ingest_source} Sage packages.")
Agreed - fixed.

2022-02-07 16:35 UTC, maxkadel commented on app/services/tasks/ingest_service.rb
> +      logger.error("Unexpected package contents - #{extracted_files.count} files extracted from #{package_path}") unless extracted_files.count.between?(2, 3)
I just went to try to verify what the ProQuest packages look like, and I'm not finding any on production or cdr-test (looking in `/opt/data/etd/unc_grad`), and the one in the fixtures directory looks like it was created by someone on the team, rather than necessarily ProQuest. Do you know if there are any packages from ProQuest directly that we could look at?

2022-02-07 16:36 UTC, maxkadel commented on app/services/tasks/ingest_service.rb
> +      logger.error("Unexpected package contents - #{extracted_files.count} files extracted from #{package_path}") unless extracted_files.count.between?(2, 3)
I like the idea of leaving this verification to the sub-class, though, in any case

2022-02-07 20:12 UTC, maxkadel commented on app/services/tasks/ingest_service.rb
> +      unless file_names.count.between?(2, 3)
I've put this validation in the subclasses

2022-02-07 20:14 UTC, maxkadel commented on app/services/tasks/ingest_service.rb
> +      logger.error("Unexpected package contents - #{extracted_files.count} files extracted from #{package_path}") unless extracted_files.count.between?(2, 3)
Found 'em - saying that a Sage should have 2 or 3 files (some have a manifest, some don't), and that ProQuest should have exactly one _Data.xml file and one or more PDF, since they can have supplemental files.

2022-02-07 20:22 UTC, maxkadel commented on spec/services/tasks/proquest_ingest_service_spec.rb
> +      expect(Dir.entries(unzipped_dir)).to match_array(['.', '..', '__MACOSX', 'attach_unc_1.pdf', 'attach_unc_1_DATA.xml', 'attach_unc_1_attach'])
I've re-zipped the file so that it looks more like the files we're getting from ProQuest, so we can leave that out now

2022-02-07 20:23 UTC, maxkadel commented on lib/tasks/proquest_ingest.rake
> +    Tasks::ProquestIngestService.new(args).process_packages
Yeah, I think that's reasonable - but naming is hard! I'll try to come up with a more different name

2022-02-07 20:58 UTC, maxkadel commented on app/services/tasks/proquest_ingest_service.rb
> +      super
I see what you're saying. I started trying to implement it, but quickly got in a snarl. I think it's starting to get more open, but I think making the method in the parent class was premature. I think the better part of valor is leaving it in the child classes until it can be more cleanly extracted.

2022-02-07 21:27 UTC, bbpennel commented on app/services/tasks/ingest_service.rb
> +      @deposit_record_hash ||= { title: "#{ingest_source} Ingest #{Time.new.strftime('%B %d, %Y')}",
Ah sorry, I remembered that it was using the progress tracker log, but I guess these two scripts are just using that for tracking rather than for tracking and resuming. It may have just been the boxc or 1science migration script which used it for resuming, and both of those use much larger batches, so it makes more sense.

2022-02-07 21:32 UTC, bbpennel approved these changes

2022-02-07 21:48 UTC, merged