WIP - may not pass in CI yet (don't have graphicsmagick on CI build)
UNC-Libraries/hy-c pull request #754
Opened 2022-02-04 20:56 UTC by maxkadel

With flipper switched to ImageMagick and all derivatives re-run

![image](https://user-images.githubusercontent.com/45948126/152599766-af3136ae-12c2-4d5e-9523-7918bb1df364.png)

2022-02-11 17:39 UTC, maxkadel commented
On cdr-test

Before:
![image](https://user-images.githubusercontent.com/45948126/153640634-d334ca43-379e-4dc9-a786-653e7f134c58.png)

After running rake task specific to file set
![image](https://user-images.githubusercontent.com/45948126/153640919-8a72dbc8-b991-40da-9c28-6e8e51d30427.png)

After running same rake task again (identical - briefly had an issue of resizing file in working directory, rather than minimagick temp file)
![image](https://user-images.githubusercontent.com/45948126/153641208-4b28bd3c-fb2b-4351-94df-ab416bfe76ba.png)

2022-02-14 16:25 UTC, bbpennel requested changes
Looks good! Do you think we will be keeping both the imagemagick and graphicsmagick logic long term, once we have switched over to using graphicsmagick everywhere?

2022-02-14 16:25 UTC, bbpennel commented on app/services/image_service.rb
> +      Rails.logger.info('[ImageProcessor] Using GraphicsMagick as image processor')
are any of the methods in this module ever going to disagree on what processor to use? If not, could potentially move the log state up into `self.processor` to centralize it. Also wondering if it should be demoted to `debug`, but it looks like its not called very many times during normal execution so don't have a strong opinion.

2022-02-14 16:25 UTC, bbpennel commented on lib/tasks/derivatives.rake
> +  desc 'Regenerates derivatives for a single thumbnail'
This isn't specific to thumbnails is it? Wondering if this should be "Regenerates derivatives for a single file set"

2022-02-14 16:25 UTC, bbpennel commented on lib/tasks/derivatives.rake
> +  desc 'Regenerates derivatives for all FileSets in the repository'
This seems like a dangerous task :)

2022-02-14 16:44 UTC, maxkadel commented on app/lib/hydra/derivatives/processors/image.rb
> +        if size
If the size it set, that means it's actively re-sizing the image, rather than using the existing size and doing some other transformation on the image, like making it black and white or changing it to a different file type. I think it's more like "Size to resize image to".

2022-02-14 16:55 UTC, maxkadel commented on lib/tasks/derivatives.rake
> +  desc 'Regenerates derivatives for all FileSets in the repository'
Yeah - I'll take it out. I used it for testing in development, but I'm not sure it's actually useful to keep.

2022-02-14 16:58 UTC, maxkadel commented on app/services/ensure_environment_service.rb
> +  def self.shared
This seems reasonable, and I'm wondering if it needs to be in this PR, or if it can be future development?

2022-02-14 16:59 UTC, bbpennel commented on app/services/ensure_environment_service.rb
> +  def self.shared
Later is fine

2022-02-14 17:16 UTC, bbpennel commented on app/lib/hydra/derivatives/processors/image.rb
> +        if size
Okay, that makes sense, I assumed the method was just for resizing stuff based off the name

2022-02-14 17:18 UTC, bbpennel approved these changes

2022-02-14 17:23 UTC, merged