HYC-1390: Create job and service to remediate affiliations
UNC-Libraries/hy-c pull request #773
Opened 2022-03-30 20:25 UTC by maxkadel

2022-04-01 15:02 UTC, bbpennel requested changes
Nice work, this looks good over all, most of my comments are about possibly reducing the number of `save!` calls or cutting down on ben confusion.

2022-04-01 15:02 UTC, bbpennel commented on spec/services/affiliation_remediation_service_spec.rb
> +    it 'can update the translator affiliations' do
I don't think any tests are currently verifying that two types of person objects get updated in a single request to `update_affiliations` right now. This one or `"with an article and general work"` could do so. 

It also might be good to demonstrate that multiple translators can get updated at the same time, since I think this test is only verifying that the first translator gets updated and that the same number of translators exist.

2022-04-01 17:00 UTC, maxkadel commented on app/services/affiliation_remediation_service.rb
> +      csv_path = 'spec/fixtures/files/umappable-affiliations-mapped-final.csv'
Yeah, I wasn't sure where to put that file. It's not something we should have to keep long-term, but we do need it for this task, and it's something we are only going to have the production version of. Do you think we should just scp it separately to maybe the /opt/data/reports/ directory or something? And have a short version of it for testing, with just the needed lines, to avoid bloat?

2022-04-01 17:27 UTC, maxkadel commented on app/services/affiliation_remediation_service.rb
> +      next unless needs_updated_people?(object, person_field)
Hrm, I can try and see how nuts it gets.

2022-04-01 17:28 UTC, maxkadel commented on app/services/affiliation_remediation_service.rb
> +      Rails.logger.debug("Mapped affiliation #{original_affiliation} to #{new_affiliation}")
Good call.

2022-04-01 17:40 UTC, maxkadel commented on spec/services/affiliation_remediation_service_spec.rb
> +                                        affiliation: unmappable_affiliation_one,
Hrm, good point, I think it's confusing because there are two kinds of mapping
1. That the affiliation term is in the current controlled vocabulary, and can be mapped from id to term and back
2. That the affiliation term is *not* in the current controlled vocabulary, but is in the special one-time mapping that Anna put together, from the uncontrolled vocab to the controlled vocab

I'll think about how I can make that distinction clearer

2022-04-01 17:40 UTC, maxkadel commented on spec/services/affiliation_remediation_service_spec.rb
> +      expect(first_creator.attributes['affiliation']).to eq(mapped_affiliation_one)
Yeah, agreed.

2022-04-01 19:57 UTC, maxkadel commented on app/services/affiliation_remediation_service.rb
> +    object.save!
I think this is going to be uncommon enough that it's not worth the complexity.

2022-04-01 19:58 UTC, maxkadel commented on app/services/affiliation_remediation_service.rb
> +      csv_path = 'spec/fixtures/files/umappable-affiliations-mapped-final.csv'
I might leave it, since this is temporary code.

2022-04-01 20:04 UTC, maxkadel commented on app/services/affiliation_remediation_service.rb
> +class AffiliationRemediationService
done

2022-04-01 20:05 UTC, maxkadel commented on spec/services/affiliation_remediation_service_spec.rb
> +                                        affiliation: unmappable_affiliation_one,
One terrible idea: `map_to_mappable_affiliation`

2022-04-01 20:14 UTC, bbpennel commented on spec/services/affiliation_remediation_service_spec.rb
> +                                        affiliation: unmappable_affiliation_one,
Maybe `remediatable_affiliation_one` to indicate when it is an affiliation that isn't in the vocab but can be remediated?

2022-04-01 20:16 UTC, bbpennel commented on app/services/affiliation_remediation_service.rb
> +    object.save!
I could see it involving building up a hash of type => new attributes, and then flushing them all at once. But I am guessing its not going to be all that common for multiple person types to need remediation on the same object

2022-04-01 20:29 UTC, maxkadel commented on spec/services/affiliation_remediation_service_spec.rb
> +  context 'with an example Article' do
done

2022-04-01 20:32 UTC, maxkadel commented on spec/services/affiliation_remediation_service_spec.rb
> +    it 'can update the creator affiliations' do
done

2022-04-01 21:02 UTC, maxkadel commented on spec/services/affiliation_remediation_service_spec.rb
> +    it 'can update the translator affiliations' do
Did the first with 'with two creators with affiliations that need to be mapped'. Since we already have this for creators, I'm not sure it's valuable to do with the translators as well.

2022-04-04 18:42 UTC, bbpennel commented on spec/services/affiliation_remediation_service_spec.rb
> +    let(:mapped_affiliation_one) { [] }
don't think this is being used anymore, can maybe remove it?

2022-04-04 18:42 UTC, bbpennel approved these changes

2022-04-04 19:09 UTC, merged