Update passenger to version 6
UNC-Libraries/hy-c pull request #804
Opened 2022-06-16 12:30 UTC by lfarrell

Trying this again as previous pr changed the github actions check and seem to have broken them. https://jira.lib.unc.edu/browse/HYC-1454

2022-06-17 16:14 UTC, cazzerson requested changes

2022-06-17 16:14 UTC, cazzerson commented on .github/workflows/build.yml
> +        ruby-version: ['2.7.6']
Should be 2.7.4

2022-06-22 13:48 UTC, bbpennel approved these changes

2022-06-22 13:53 UTC, cazzerson approved these changes

2022-06-22 14:00 UTC, merged