HYC-1493 - Coverage/overrides for statistics classes
UNC-Libraries/hy-c pull request #828
Opened 2022-07-18 18:37 UTC by bbpennel

https://jira.lib.unc.edu/browse/HYC-1493

* Adds test coverage for overrides in statistic.rb, file_download_stats.rb, and download.rb
* Converts statistic.rb and file_download_stats.rb to overrides (not sure how to do/verify this for download.rb so left it alone)

2022-07-19 21:24 UTC, sharonluong requested changes

2022-07-19 21:24 UTC, sharonluong commented on spec/models/file_download_stat_spec.rb
> +      context 'when a profile not available' do
can you change this to "is not available"?

2022-07-19 21:24 UTC, sharonluong commented on spec/models/hyrax/statistic_spec.rb
> +      context 'when a profile not available' do
same here

2022-07-19 21:24 UTC, sharonluong commented on spec/models/hyrax/statistic_spec.rb
> +        expect(stats.map(&:to_flot)).to include([work_view_stat.date.to_i * 1000, work_view_stat.work_views], *view_output)
what does `to_flot` do?

2022-07-20 12:46 UTC, bbpennel commented on spec/models/hyrax/statistic_spec.rb
> +        expect(stats.map(&:to_flot)).to include([work_view_stat.date.to_i * 1000, work_view_stat.work_views], *view_output)
converts a string to a number. This particular test is copied from hyrax since it provides coverage of the unchanged parts of our override, so I mostly trusted that they knew what they were doing with the expectations.

2022-07-20 12:48 UTC, bbpennel commented on spec/models/file_download_stat_spec.rb
> +      context 'when a profile not available' do
updated

2022-07-20 14:29 UTC, bbpennel commented on spec/models/hyrax/statistic_spec.rb
> +        expect(stats.map(&:to_flot)).to include([work_view_stat.date.to_i * 1000, work_view_stat.work_views], *view_output)
well, i lied, its calling the "to_flot" method defined in statistic.rb, which appears to be converting the inputs into coordinates for a graph. It'd be nice if it had any sort of description

2022-07-20 15:49 UTC, merged