Draft: Only pull in the parts of the collection form we override and add tests
UNC-Libraries/hy-c pull request #842
Opened 2022-08-23 20:36 UTC by lfarrell

https://jira.lib.unc.edu/browse/HYC-1488

2022-08-24 20:17 UTC, bbpennel requested changes
Very satisfying seeing so much deletion!

2022-08-24 20:17 UTC, bbpennel commented on spec/forms/hyrax/collection_form_spec.rb
> +  describe '#secondary_terms' do
How do we decide whether to use a . or a # in front of the name of the method being tested? Is it based on whether it is a class or instance method, or something else? Wondering since `terms` is a class variable and `seconary_terms` is an instance method

2022-08-24 20:17 UTC, bbpennel commented on spec/forms/hyrax/collection_form_spec.rb
> +  let(:form) { described_class.new(collection, nil, repository) }
If these are only used for `secondary_terms`, could probably move these inside its `describe`

2022-08-24 20:17 UTC, bbpennel commented on spec/forms/hyrax/collection_form_spec.rb
> +  describe '.build_permitted_params' do
I'm not sure we need to test this, since we aren't overriding anything in it for collection_form. I assume its coming from one of the includes, and is based on the fields in terms, so should adapt as long as terms has the right value

2022-08-25 12:52 UTC, lfarrell commented on spec/forms/hyrax/collection_form_spec.rb
> +  describe '#secondary_terms' do
Seems like . for class methods and # for instance methods, https://www.betterspecs.org/

2022-08-25 13:02 UTC, bbpennel approved these changes

2022-08-25 13:59 UTC, merged