Move indexing override to overrides directory. Remove methods we don't override
UNC-Libraries/hy-c pull request #847
Opened 2022-08-25 20:26 UTC by lfarrell

https://jira.lib.unc.edu/browse/HYC-1505

I think this if fixed in Hyrax 3 and can be removed when we upgrade, https://github.com/samvera/hyrax/blame/main/app/indexers/hyrax/deep_indexing_service.rb#L99

2022-08-26 13:18 UTC, bbpennel requested changes
It looks like test coverage went down in this PR. Annoyingly, I can't tell from codeclimate which parts are not covered, but my guess is the removal of unoverridden code removed a lot of the parts that were being tested. I'm guessing we might need to add a test for the case where we fail to retrieve geonames, but running the test in docker should give a better coverage report

2022-08-29 14:08 UTC, bbpennel requested changes
You might already know about this, but you can view the test coverage report on your local computer after running it in docker by going to 
`file:///path/to/hy-c/coverage/index.html`
and click through to individual files to see which lines aren't being called. It really seems like there must be a way to see that in codeclimate, but I haven't seen it yet.

2022-08-29 14:08 UTC, bbpennel commented on spec/indexers/hyrax/deep_indexing_service_spec.rb
> +                 'User-Agent' => 'Ruby'
Since the headers aren't something we are setting ourselves, and seem to be constant, I am guessing we can leave this `with` clause out, which should help some with readability. I think we can remove the other two `with(headers` sections as well

2022-08-29 14:08 UTC, bbpennel commented on spec/indexers/hyrax/deep_indexing_service_spec.rb
> +      chapel_hill = <<RDFXML.strip_heredoc
Maybe name include a little more context in the variable name, like `geo_resp_chapel_hill` or something. Also wasn't sure if this should be in a `let()` block?

2022-08-30 20:20 UTC, bbpennel requested changes

2022-08-30 20:20 UTC, bbpennel commented on app/overrides/indexers/hyrax/deep_indexing_service_override.rb
> +# [hyc-override] Overriding to add method to return custom label and save it to Solr
Lets link to the file this overrides
https://github.com/samvera/hyrax/blob/v2.9.6/app/indexers/hyrax/deep_indexing_service.rb

2022-08-30 20:20 UTC, bbpennel commented on app/overrides/indexers/hyrax/deep_indexing_service_override.rb
> +  def geonames_mail(e)
Is it typical practice to define a method like this for sending the email rather than calling the mailer directly in the rescue block?

2022-08-30 20:20 UTC, bbpennel commented on spec/indexers/hyrax/deep_indexing_service_spec.rb
> +        allow(service).to receive(:geonames_mail).and_return(mail_sent)
I'd suggest doing 
`allow(GeonamesMailer).to receive(:send_mail).and_return(mail_sent)`
since this is a unit test, so it makes sense to mock an external class for this test, rather than mocking a part of the class we are testing. I'd do the same for the `expect` down below as well

2022-08-30 20:20 UTC, bbpennel commented on spec/indexers/hyrax/deep_indexing_service_spec.rb
> +            headers: {
Does the stubbing still match without specifying the expected headers? Because a human list of Accepts like this seems like it could change pretty easily when the geonames gem gets updated, and it doesn't seem very important to what we're testing.

2022-08-31 12:24 UTC, lfarrell commented on app/overrides/indexers/hyrax/deep_indexing_service_override.rb
> +  def geonames_mail(e)
Probably not. It's called directly now.

2022-09-01 13:06 UTC, bbpennel approved these changes

2022-09-01 13:06 UTC, merged