Add tests for date attribute renderer
UNC-Libraries/hy-c pull request #851
Opened 2022-08-30 18:05 UTC by lfarrell

https://jira.lib.unc.edu/browse/HYC-1497

2022-08-30 21:04 UTC, bbpennel requested changes
Just one suggestion and a little confusion

2022-08-30 21:04 UTC, bbpennel commented on spec/renderers/hyrax/renderers/data_attribute_renderer_spec.rb
> +      it { expect(renderer).not_to be_microdata(field) }
I see this is from the hyrax tests, i'm honestly not sure what its testing though

2022-08-31 12:28 UTC, lfarrell commented on spec/renderers/hyrax/renderers/data_attribute_renderer_spec.rb
> +      it { expect(renderer).not_to be_microdata(field) }
Yeah, I just copied it over. I'll remove those.

2022-09-01 13:02 UTC, bbpennel approved these changes

2022-09-01 13:02 UTC, merged