Add tests for publication behavior overrides
UNC-Libraries/hy-c pull request #859
Opened 2022-09-12 13:01 UTC by lfarrell

https://jira.lib.unc.edu/browse/HYC-1504

2022-09-12 19:28 UTC, bbpennel requested changes

2022-09-12 19:28 UTC, bbpennel commented on spec/helpers/hyrax/citations_behaviors/publication_behavior_spec.rb
> +    let(:work_with_date_issued) {
In terms of test structure, I think it'd make sense for the top level to be `describe '#setup_pub_date'` and then have 4 contexts inside of it, one for each of the example articles, since they each represent a test scenario/context. Then the context info can be moved from the `it` message into the context description.

2022-09-12 19:28 UTC, bbpennel commented on spec/helpers/hyrax/citations_behaviors/publication_behavior_spec.rb
> +  context 'with a publication place' do
Similar suggestion to above, have a `describe '#setup_pub_place'` here, and then contexts for the two attribute sets inside of it

2022-09-12 20:15 UTC, lfarrell commented on spec/helpers/hyrax/citations_behaviors/publication_behavior_spec.rb
> +  context 'with a publication place' do
Removed override for setup_pub_info. Local override breaks tests for https://github.com/UNC-Libraries/hy-c/blob/main/spec/helpers/hyrax/citations_behaviors/formatters/apa_formatter_spec.rb

2022-09-15 21:11 UTC, bbpennel approved these changes
I guess we care more about stray commas than hyrax does. Good work

2022-09-15 21:12 UTC, merged