BXC-1665 - Notification fixes
UNC-Libraries/hy-c pull request #971
Opened 2023-05-12 19:33 UTC by bbpennel

https://jira.lib.unc.edu/browse/HYC-1665
* Don't send deletion approval email to managers, except when an admin performs a withdraw action directly
* Don't send "needs review" emails to depositors, only to approvers

2023-05-15 21:55 UTC, sharonluong requested changes

2023-05-15 21:55 UTC, sharonluong commented on app/services/hyrax/workflow/withdrawl_notification.rb
> +    class WithdrawlNotification < DeletionApprovalNotification
Withdrawal is misspelled =) can you rename it in all the locations?

2023-05-15 21:55 UTC, sharonluong commented on app/overrides/services/hyrax/workflow/pending_review_notification_override.rb
> +      super
where is super defined?

2023-05-15 21:55 UTC, sharonluong commented on spec/services/hyrax/workflow/withdrawl_notification_spec.rb
> +    it 'sends a message to depositor and user who instigated action' do
the depositor doesn't seem to get a message in the following test. only the approver?

2023-05-16 14:00 UTC, bbpennel commented on app/services/hyrax/workflow/withdrawl_notification.rb
> +    class WithdrawlNotification < DeletionApprovalNotification
I have withdrawn the misspelled class name

2023-05-16 14:01 UTC, bbpennel commented on app/overrides/services/hyrax/workflow/pending_review_notification_override.rb
> +      super
Its defined by ruby, it refers to the parent class or the parent class' implementation of the same method

2023-05-16 14:05 UTC, sharonluong commented on app/overrides/services/hyrax/workflow/pending_review_notification_override.rb
> +      super
ohh right

2023-05-16 14:09 UTC, sharonluong approved these changes

2023-05-16 14:52 UTC, merged