HYC-1687 - DOI script fixes
UNC-Libraries/hy-c pull request #979
Opened 2023-06-08 21:02 UTC by bbpennel

https://jira.lib.unc.edu/browse/HYC-1687

* Converts languages to iso639-1, which is the required format for languages in datacite
    * Language vocab now has iso639-1 values when one exists.
* Removes contributors from datacite request as they are no longer supported by its API
* Excludes items without publication dates from receiving a DOI (it is a required field)
* Items with invalid publication dates will fall back to the date the work was created (dates must be YYYY)
* Dates that are in decade/century format will converted back an actual date (18xx becomes 1800)
* resourceTypeGeneral now falls back to 'Text' if we are unable to determine a value (it is a required field). resourceType falls back to the resourceTypeGeneral if none is available (also a required field)

2023-06-12 17:48 UTC, sharonluong requested changes

2023-06-12 17:48 UTC, sharonluong commented on app/services/languages_service.rb
> +  rescue KeyError
so if it can't find the iso639_1 version then it will return nil?

2023-06-12 17:48 UTC, sharonluong commented on app/services/tasks/doi_create_service.rb
> +        data[:data][:attributes][:language] = lang_code unless lang_code.blank?
what does `data[:data][:attributes][:language]` get set to if lang_code is blank?

2023-06-12 17:48 UTC, sharonluong commented on app/services/tasks/doi_create_service.rb
> +    def extract_publication_year(work)
i feel like using a verb here is a java convention?

2023-06-12 17:48 UTC, sharonluong commented on app/services/tasks/doi_create_service.rb
> +        puts "#{get_time} WARNING: Unable to determine resourceTypeGeneral for record" if datacite_type.nil?
i think the `if datacite_type.nil?` check here isn't needed since it's checked in line 253 already

2023-06-12 17:48 UTC, sharonluong commented on app/services/tasks/doi_create_service.rb
> +        result[:resourceType] = record_type.first unless record_type.blank?
don't need the `unless record_type.blank?` here

2023-06-12 17:48 UTC, sharonluong commented on app/services/tasks/doi_create_service.rb
> +      end
hmm or you could use a ternary like

result[:resourceType] = record_type.present? ? record_type.first : datacite_type

2023-06-12 19:33 UTC, bbpennel commented on app/services/tasks/doi_create_service.rb
> +        data[:data][:attributes][:language] = lang_code unless lang_code.blank?
nothing, no language attribute would be supplied. Its a recommended but not required field.

2023-06-12 19:37 UTC, bbpennel commented on app/services/tasks/doi_create_service.rb
> +        puts "#{get_time} WARNING: Unable to determine resourceTypeGeneral for record" if datacite_type.nil?
good catch

2023-06-13 14:31 UTC, sharonluong approved these changes

2023-06-13 14:32 UTC, merged