WIP: Hyc 1686 manually delete package
UNC-Libraries/hy-c pull request #986
Opened 2023-07-11 21:08 UTC by sharonluong

https://jira.lib.unc.edu/browse/HYC-1686

2023-07-28 20:45 UTC, bbpennel requested changes
Looks good based on reading, just some suggestions for tidying up

2023-07-28 20:45 UTC, bbpennel commented on app/controllers/ingest_from_ftp_controller.rb
> +      if selected_filenames.any? { |filename| package_path.include?(filename) }
Another approach could be to loop through `selected_filenames` and delete `File.join(storage_base_path, File.basename(selected_filename))` if it exists (with the basename part to make sure the user doesn't include as "../" in the filename or try to change directories).

If we want to keep the current approach, would it make sense to call `list_selected_package_paths` and delete everything in that instead? It looks like it would only include filenames that exist in the sage/proquest directory.

2023-07-28 20:45 UTC, bbpennel commented on app/controllers/ingest_from_ftp_controller.rb
> +      if selected_filenames.any? { |filename| package_path.include?(filename) }
```suggestion
      if selected_filenames.any? { |filename| File.basename(package_path) == filename }
```
since we're only concerned with the filename part and it'd eliminate the very small chance of filename matching only part of the path (either in the parent directories or a partial filename match).

2023-07-28 20:45 UTC, bbpennel commented on app/views/ingest_from_ftp/list_packages.html.erb
> +        checkboxes.prop("checked",true);
```suggestion
      if (checkboxes.prop("checked")){
        checkboxes.prop("checked", false);
      } else {
        checkboxes.prop("checked", true);
```

2023-07-28 20:45 UTC, bbpennel commented on spec/controllers/ingest_from_ftp_controller_spec.rb
> +          end
```suggestion
        expect(IngestFromProquestJob).to have_received(:perform_later) do |arg1, arg2|
          expect(arg1).to eq(user.uid)
          expect(arg2).to match_array([proquest_package1, proquest_package2])
        end
```

2023-07-28 20:45 UTC, bbpennel commented on spec/controllers/ingest_from_ftp_controller_spec.rb
> +      it 'deletes a proquest ingest job and returns to the same page' do
```suggestion
      it 'deletes a proquest ingest package and returns to the same page' do
```

2023-07-28 20:45 UTC, bbpennel commented on spec/controllers/ingest_from_ftp_controller_spec.rb
> +      existing_filenames = filename_array.map { |path| path.split('/').last }
```suggestion
      existing_filenames = filename_array.map { |path| File.basename(path) }
```

2023-07-28 20:45 UTC, bbpennel commented on spec/controllers/ingest_from_ftp_controller_spec.rb
> +        expect(package_filepaths.empty?).to eq true
```suggestion
        expect(package_filepaths).to be_empty
```
Just a handy built in check, same outcome of course

2023-07-31 15:18 UTC, sharonluong commented on app/controllers/ingest_from_ftp_controller.rb
> +      if selected_filenames.any? { |filename| package_path.include?(filename) }
I like the second approach. When I did the delete feature I didn't have that method yet, I made it as part of the ingest selected package work.

2023-07-31 21:24 UTC, bbpennel approved these changes

2023-08-17 17:14 UTC, merged